include:
  - ../compose.yaml

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      #no_cache: true
    env_file:
      - path: ../.env
        required: false
    volumes:
      # Mount only the necessary files
      - ../vscode-markdown-marker-tools:/workspace/vscode-markdown-marker-tools:cached
      - ../.devcontainer:/workspace/.devcontainer:cached
      - ../.vscode:/workspace/.vscode:cached
      - ../docs:/workspace/docs:ro
      - ../.env.example:/workspace/.env.example:ro
      - ../compose.yaml:/workspace/compose.yaml:ro
      # Optionally, you can mount the entire workspace if needed
      # - ..:/workspace:cached
    command: sleep infinity
